# Generated by Django 5.2.13 on 2026-06-05 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0013_alter_horariodisponible_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código QR')),
                ('presente', models.BooleanField(default=False, verbose_name='Presente')),
                ('fecha_registro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de registro')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='turnos.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
