# Generated by Django 5.2.13 on 2026-05-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('employee', 'Empleado'), ('user', 'Cliente')], default='user', max_length=20, verbose_name='Rol'),
        ),
    ]
