# Generated by Django 5.2.13 on 2026-05-20 06:15

from django.db import migrations
from django.contrib.auth.hashers import make_password


def crear_admin_defecto(apps, schema_editor):
    Usuario = apps.get_model('accounts', 'Usuario')
    if not Usuario.objects.filter(email='admin@admin.com').exists():
        admin_user = Usuario(
            email='admin@admin.com',
            nombre='Admin',
            apellido='Club360',
            nro_documento='00000000',
            fecha_nacimiento='2000-01-01',
            rol='admin',
            is_staff=True,
            is_superuser=True,
            is_active=True
        )
        admin_user.password = make_password('Admin360!')
        admin_user.save()


def eliminar_admin_defecto(apps, schema_editor):
    Usuario = apps.get_model('accounts', 'Usuario')
    Usuario.objects.filter(email='admin@admin.com').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_rol'),
    ]

    operations = [
        migrations.RunPython(crear_admin_defecto, reverse_code=eliminar_admin_defecto),
    ]

