# Generated by Django 5.2.13 on 2026-05-29 15:52

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_suspendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nro_documento',
            field=models.CharField(max_length=20, unique=True, validators=[apps.accounts.models.validar_dni], verbose_name='Número de documento'),
        ),
    ]
