# Generated by Django 5.2.13 on 2026-07-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usuario_nro_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='monto_adeudado_suspension',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto a pagar para levantar la suspensión'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='suspendido',
            field=models.BooleanField(default=False, help_text='Suspensión global como no abonado por incumplir el pago de 3 clases sueltas en el mismo mes. No permite reservar turnos sueltos de ningún deporte.', verbose_name='Suspendido'),
        ),
    ]
