# Generated by Django 5.2.13 on 2026-07-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usuario_monto_adeudado_suspension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='suspendido',
            field=models.BooleanField(default=False, help_text='Suspensión global como no abonado por no asistir a 3 clases sueltas señadas sin completar el pago en el mismo mes.', verbose_name='Suspendido'),
        ),
    ]
