"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3yug%(5agj8hd+bba&%rqms^o=u(u7!*yb+t8lj4m3ntkcc^2p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',
    'core',
    'apps.accounts',
    'apps.actividades',
    'apps.turnos',
    'apps.pagos',
    'apps.creditos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ─────────────────────────────────────────────
#  Modelo de usuario personalizado
#  Debe declararse ANTES de la primera migración.
#  'accounts' es la app que contiene el modelo Usuario.
# ─────────────────────────────────────────────
AUTH_USER_MODEL = 'accounts.Usuario'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        # Bloquea contraseñas similares a los datos del usuario
        # (email, nombre, apellido, nro_documento)
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('email', 'nombre', 'apellido', 'nro_documento'),
        },
    },
    {
        # Longitud mínima de 8 caracteres
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        # Bloquea contraseñas de uso común (rockyou.txt, etc.)
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Bloquea contraseñas puramente numéricas
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ─────────────────────────────────────────────
#  Hasheo de contraseñas
#  PBKDF2+SHA256 con salt aleatorio (Django default).
#  El hasher más seguro siempre va primero.
#  Para usar Argon2: pip install django[argon2]
#  y descomentar la línea correspondiente.
# ─────────────────────────────────────────────
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    # 'django.contrib.auth.hashers.Argon2PasswordHasher',
]


# ─────────────────────────────────────────────
#  Seguridad de sesiones y cookies
# ─────────────────────────────────────────────
SESSION_COOKIE_HTTPONLY = True   # La cookie de sesión no es accesible desde JS
SESSION_COOKIE_SAMESITE = 'Lax'  # Mitigación CSRF entre sitios
SESSION_COOKIE_AGE = 3600        # Sesión expira en 1 hora

CSRF_COOKIE_HTTPONLY = False      # Necesario para requests AJAX con CSRF
CSRF_COOKIE_SAMESITE = 'Lax'

# En producción con HTTPS, descomentar:
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_SSL_REDIRECT = True


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

COMPRESS_ROOT = BASE_DIR / 'static'

COMPRESS_ENABLED = True

STATICFILES_FINDERS = ('compressor.finders.CompressorFinder',)

# ─────────────────────────────────────────────
#  Correo (recuperación de contraseña)
#
#  Si las variables de entorno EMAIL_HOST_USER y EMAIL_HOST_PASSWORD están
#  seteadas (típicamente en un archivo .env local), se envían mails reales
#  vía SMTP de Gmail. Si no, se cae al backend de consola para no romper
#  el setup de desarrolladores que aún no configuraron el .env.
#
#  Para Gmail: habilitá 2FA y generá un App Password en
#  https://myaccount.google.com/apppasswords
#  Ver .env.example en la raíz del proyecto.
# ─────────────────────────────────────────────
if os.environ.get('EMAIL_HOST_USER'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
    EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
    EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
    DEFAULT_FROM_EMAIL = os.environ.get(
        'DEFAULT_FROM_EMAIL', f'Club360 <{EMAIL_HOST_USER}>'
    )
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'Club360 <noreply@club360.local>'

#redirección del login

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# ─────────────────────────────────────────────
#  Logging
#  Registra eventos de la app accounts (login, logout,
#  creación de usuarios, errores) en consola y archivo.
#  Crear el directorio antes de correr: mkdir logs
# ─────────────────────────────────────────────
import logging.handlers  # noqa: E402

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'archivo_accounts': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'accounts.log',
            'maxBytes': 5 * 1024 * 1024,  # 5 MB por archivo
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Logs de la app accounts (autenticación, usuarios)
        'accounts': {
            'handlers': ['console', 'archivo_accounts'],
            'level': 'INFO',
            'propagate': False,
        },
        # Alertas de seguridad de Django (intentos de CSRF, etc.)
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}