# Generated by Django 5.2.13 on 2026-05-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_seed_actividades'),
        ('turnos', '0002_turno_cupos'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turno',
            name='unique_turno_actividad_fecha_hora',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_reserva',
            field=models.CharField(choices=[('individual', 'Turno individual'), ('mensual', 'Mensual (mismo día y hora, todo el mes)')], default='individual', help_text='Indica si esta reserva es parte de una serie mensual o es individual.', max_length=10, verbose_name='Tipo de reserva'),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('actividad', 'fecha', 'hora')},
        ),
    ]
