# Generated by Django 5.2.13 on 2026-05-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_grupo_regla_cobro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruporeservamensual',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Abonado mensual', 'verbose_name_plural': 'Abonados mensuales'},
        ),
        migrations.AddField(
            model_name='turno',
            name='precio_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se completa, reemplaza el precio de la actividad.', max_digits=10, null=True, verbose_name='Precio especial (override)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pago pendiente'), ('senado', 'Señado'), ('pagado', 'Pagado')], default='pendiente', max_length=10, verbose_name='Estado de pago'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_reserva',
            field=models.CharField(choices=[('individual', 'Turno único'), ('varios', 'Abonado mensual'), ('mensual', 'Abonado mensual')], default='individual', help_text='Indica si esta reserva es parte de una serie mensual o es individual.', max_length=10, verbose_name='Tipo de reserva'),
        ),
    ]
