# Generated by Django 5.2.13 on 2026-05-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_alter_gruporeservamensual_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='precio_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se completa, reemplaza el precio de la actividad.', max_digits=10, null=True, verbose_name='Precio'),
        ),
    ]
