# Generated by Django 5.2.13 on 2026-05-23 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_alter_turno_precio_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelacionAbonoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_cancelacion', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('mes_cancelacion', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones_abono_registradas', to='turnos.reserva', verbose_name='Reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelaciones_abono_mensual', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cancelación abono mensual',
                'verbose_name_plural': 'Cancelaciones abono mensual',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['usuario', 'anio_cancelacion', 'mes_cancelacion'], name='cancel_abono_usuario_mes_idx')],
            },
        ),
    ]
