# Generated by Django 5.2.13 on 2026-05-29 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_actualizar_precios'),
        ('turnos', '0008_cancelacionabonomensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')], verbose_name='Día de la semana')),
                ('hora', models.PositiveSmallIntegerField(help_text='Hora entera. El turno dura 1 hora.', verbose_name='Hora de inicio')),
                ('cupos', models.PositiveIntegerField(blank=True, help_text='Cupos disponibles. Si se deja vacío se toma el valor de la actividad.', null=True, verbose_name='Cupos')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar impide que se generen nuevos turnos, pero no cancela los existentes.', verbose_name='Activo')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponibles', to='actividades.actividad', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Horario disponible',
                'verbose_name_plural': 'Horarios disponibles',
                'ordering': ['dia_semana', 'hora', 'actividad'],
                'unique_together': {('actividad', 'dia_semana', 'hora')},
            },
        ),
    ]
