# Generated by Django 5.2.13 on 2026-05-29 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_horariodisponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodisponible',
            name='cupos',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cupos'),
        ),
    ]
