# Generated by Django 5.2.13 on 2026-05-29 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_alter_horariodisponible_cupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodisponible',
            name='cupos',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cupos'),
        ),
    ]
