# Generated by Django 5.2.13 on 2026-05-29 04:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0011_alter_horariodisponible_cupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodisponible',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('8500.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio'),
        ),
    ]
