# Generated by Django 5.2.13 on 2026-06-15 05:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0013_alter_horariodisponible_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionCupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de vencimiento')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
            ],
            options={
                'verbose_name': 'Invitación de cupo',
                'verbose_name_plural': 'Invitaciones de cupo',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_reserva_activa_por_usuario_turno',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('en_espera', 'En lista de espera'), ('invitado', 'Invitado (esperá confirmación)'), ('cancelada', 'Cancelada')], default='confirmada', max_length=12, verbose_name='Estado'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['confirmada', 'en_espera', 'invitado'])), fields=('usuario', 'turno'), name='unique_reserva_activa_por_usuario_turno'),
        ),
        migrations.AddField(
            model_name='invitacioncupo',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitacion', to='turnos.reserva', verbose_name='Reserva'),
        ),
    ]
