# Generated by Django 5.2.13 on 2026-07-01 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_actualizar_precios'),
        ('turnos', '0014_invitacioncupo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspensionAbonado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('plazo_vencido', 'Abono impago al día 11'), ('tres_canceladas', '3 clases canceladas en el mes')], max_length=20, verbose_name='Motivo')),
                ('monto_adeudado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto a pagar para levantar la suspensión')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suspensión')),
                ('fecha_levantamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de levantamiento')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensiones_abonado', to='actividades.actividad', verbose_name='Actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensiones_abonado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suspensión de abonado',
                'verbose_name_plural': 'Suspensiones de abonado',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
