# Generated by Django 5.2.13 on 2026-07-01 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_actualizar_precios'),
        ('turnos', '0015_suspensionabonado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelacionAbonoConfirmada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la clase')),
                ('anio_cancelacion', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('mes_cancelacion', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelaciones_abono_confirmadas', to='actividades.actividad', verbose_name='Actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelaciones_abono_confirmadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cancelación de abono confirmada',
                'verbose_name_plural': 'Cancelaciones de abono confirmadas',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['usuario', 'actividad', 'anio_cancelacion', 'mes_cancelacion'], name='cancel_abono_conf_idx')],
            },
        ),
    ]
