# Generated by Django 5.2.13 on 2026-07-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0016_cancelacionabonoconfirmada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspensionabonado',
            name='motivo',
            field=models.CharField(choices=[('plazo_vencido', 'Abono impago al día 11')], max_length=20, verbose_name='Motivo'),
        ),
        migrations.DeleteModel(
            name='CancelacionAbonoConfirmada',
        ),
    ]
