# Generated by Django 5.2.13 on 2026-07-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0017_alter_suspensionabonado_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cancelado_por_club',
            field=models.BooleanField(default=False, help_text='El club canceló esta clase puntual (sin borrar la franja semanal). No se puede volver a reservar ni se recrea automáticamente.', verbose_name='Cancelado por el club'),
        ),
    ]
